apiVersion: v1
kind: PersistentVolume
metadata:
  name: weightr-frontend-pv
  labels:
    app: weightr-frontend
    datatype: conf
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: manual-hostpath
  hostPath:
    path: {{ .Values.storage.hostPath }}