apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-weightr-frontend-conf
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual-hostpath    # Match this with PV
