apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weightr-frontend
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  {{- if .Values.ingress.host }}
  # ── PRODUCTION: host-based routing ────────────────
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: weightr-frontend
            port:
              number: 8501
  {{- else }}
  # ── DEVELOPMENT: no host, catch-all rule ─────────
  - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: weightr-frontend
              port:
                number: 8501
  {{- end }}