image:
  repository: weightr-frontend
  tag: latest
  pullPolicy: IfNotPresent

deploymentEnv: dev.docker

storage:
  hostPath: /mnt/var/conf/weightr-frontend

resources:
  limits:
    cpu: "0.5"
    memory: "512Mi"
  requests:
    cpu: "0.1"
    memory: "256Mi"
